appname: app-manuals
tier: backend
protocol: TCP
port: 8084
nodePort: 30004
type: NodePort
replicas: 1
image:
  repository: 127.0.0.1:5000/app-manuals
  tag: latest
  pullPolicy: Always
env:
  postgresUser: postgres
  postgresPassword: postgres
  postgresDb: bank
  postgresHost: postgres-service
  profile: kuber